# Generated by Django 3.2.5 on 2021-07-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210729_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_title', models.CharField(blank=True, max_length=20)),
                ('cover_description', models.CharField(blank=True, max_length=30)),
                ('cover_image', models.ImageField(upload_to='photos/covers')),
            ],
        ),
    ]
