# Generated by Django 3.2.5 on 2021-08-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('size', 'размер'), ('color', 'цвет')], max_length=100),
        ),
    ]
