# Generated by Django 3.2.5 on 2021-08-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpassword',
            name='surname',
            field=models.CharField(default='exit', max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
